Repository graalvm/mandrel, pull requests merged in 2020-12, with the labels that each got.

#181 [CI] Update workflow to get the matrix from json file
  .github/workflows/mandrel.yml
Labels: affects/20.3, oca-signed, testing

#183 Rework passing of arguments between the driver and the native-image generator runner
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java
Labels: affects/20.3, backport, bug, oracle-emp

#186 Fix UnsatisfiedLinkError when using ImageIO and jpeg
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
Labels: oca-signed

#182 [CI] Update workflow to get the matrix from json file
  .github/workflows/mandrel.yml
Labels: oca-signed, testing
