Repository graalvm/mandrel, pull requests merged in 2020-08, with the labels that each got.

#85 Add GH actions and Mandrel readme
  .github/mvn-settings.xml
  .github/workflows/quarkus.yml
  README-Mandrel.md
  README.md
Labels: enhancement, oca-signed

#89 Enforce consistent lookup of class and file names
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
Labels: backport, bug, oca-signed

#87 Enable assertions in CI
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#92 Sync CI workflow with quarkus
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#94 Sync CI workflow with mandrel/20.1
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#91 Keep image zone rules cache separate #2637
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_time_zone_ZoneRules.java
Labels: backport, oca-signed

#96 README: mention that Mandrel doesn't support the image build server
  README-Mandrel.md
Labels: documentation, oca-signed

#99 Test mandrel/20.1 against branch 1.7 instead of latest release
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#104 Bump version in suites
  compiler/mx.compiler/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: oca-signed

#113 Introduce `not-Stale` label to mark non-stale issues
  .github/workflows/mark-stale-issues-and-prs.yml
Labels: enhancement, oca-signed

#112 Mandrel/20.1 add jdk ea to matrix
  .github/workflows/quarkus.yml
Labels: enhancement, oca-signed, testing

#100 Update mandrel-readme regarding the build image server in mandrel/20.2.
  README-Mandrel.md
Labels: documentation, enhancement, oca-signed
