Repository graalvm/mandrel, pull requests merged in 2020-06, with the labels that each got.

#31 Run quarkus tests on pull requests in addition to pushes
  .github/workflows/quarkus.yml
Labels: testing

#34 Capture NoClassDefFoundError and report with source type
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
Labels: backport

#44 Opens PR when a new OpenJDK EA release comes out
  .github/workflows/repo-sync.yml
Labels: oca-signed, testing

#38 Adds README-Mandrel.md
  README-Mandrel.md
  README.md
Labels: documentation, oca-signed

#53 fixup! Adds README\-Mandrel.md
  README-Mandrel.md
Labels: documentation, oca-signed

#52 Adds README-Mandrel.md
  README-Mandrel.md
  README.md
Labels: documentation, oca-signed

#56 Use redhat email in merges to make oca-bot happy
  .github/workflows/repo-sync.yml
Labels: bug, oca-signed

#58 Documentation: Ubuntu-like system dependencies
  README-Mandrel.md
Labels: documentation, oca-signed

#59 Documentation: Ubuntu-like system dependencies
  README-Mandrel.md
Labels: documentation, oca-signed

#57 Use mandrel-packaging in GH workflow
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#60 [20.1 backport] Remote attach options are not only ports #2532
  substratevm/src/com.oracle.svm.driver/resources/HelpExtra.txt
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
Labels: backport, oca-signed

#48 Automatically marks stale issues and PRs
  .github/workflows/mark-stale-issues-and-prs.yml
Labels: oca-signed

#62 Fixes for slack in README-Mandrel
  README-Mandrel.md
Labels: documentation, oca-signed

#61 Update issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/0_feature_request.md
  .github/ISSUE_TEMPLATE/1_issues_native_image.md
  .github/ISSUE_TEMPLATE/2_issues_truffle.md
  .github/ISSUE_TEMPLATE/3_issues_tools.md
  .github/ISSUE_TEMPLATE/4_issues_llvm.md
  .github/ISSUE_TEMPLATE/5_issues_other.md
Labels: documentation, enhancement, oca-signed

#63 Fixes for slack in README-Mandrel
  README-Mandrel.md
Labels: documentation, oca-signed

#67 Use new location of mandrel-packaging in github workflow
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#65 Update github workflow to use mandrel-packaging
  .github/workflows/quarkus.yml
Labels: enhancement, oca-signed, testing

#66 Mandrel/20.1 fix travis
  .travis.yml
Labels: backport, enhancement, oca-signed, testing

#69 Update CI to match that of quarkus
  .github/workflows/quarkus.yml
Labels: bug, oca-signed, testing

#70 Update CI to match that of quarkus
  .github/workflows/quarkus.yml
Labels: oca-signed, testing
