Repository graalvm/mandrel, pull requests merged in 2020-10, with the labels that each got.

#140 Update quarkus CI workflow
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#142 Do not raise an error if incomplete classpath is allowed
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
Labels: oca-signed

#143 [20.1] Remove cancel-previous-runs to conform to new rules and skipDocs
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#144 [20.2] Remove cancel-previous-runs ro conform to new rules + backport of #140
  .github/workflows/quarkus.yml
Labels: oca-signed, testing

#153 CI: Test against both GA and EA versions of OpenJDK
  .github/workflows/quarkus.yml
Labels: affects/20.2, testing

#155 Clear lower half of two-slot value when upper half is not live
  compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/FrameStateBuilder.java
Labels: affects/20.2, backport, bug

#160 README: remove libffi-devel dependency
  README-Mandrel.md
Labels: affects/20.2, documentation

#161 README: remove libffi-devel dependency
  README.md
Labels: documentation

#159 README: remove libffi-devel dependency
  README-Mandrel.md
Labels: affects/20.1, documentation

#157 Clear lower half of two-slot value when upper half is not live
  compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/FrameStateBuilder.java
Labels: affects/20.1, backport, bug
