Repository graalvm/mandrel, pull requests merged in 2021-11, with the labels that each got.

#313 CI: Disable nightly pipeline on PRs
  .github/workflows/nightly.yml
Labels: testing, oca-signed

#312 CI: Quarkus main is now using GraalVM/Mandrel 21.3
  .github/workflows/nightly.yml
Labels: testing, oca-signed

#260 CI: Add job to run mandrel-integration-tests
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: enhancement, testing, oca-signed, not-Stale

#315 Support removal of java.net.Inet6Address.cached_scope_id in 11.0.14+1
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJavaNet.java
Labels: backport, oracle-emp, affects/21.2

#317 CI: Add windows and linux workflows for 21.3 branch
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
  .github/workflows/main.yml
Labels: testing, oca-signed, affects/21.3

#319 CI: Add windows and linux workflows for 21.2 branch
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
  .github/workflows/main.yml
Labels: testing, oca-signed, affects/21.2

#320 CI: Switch to adoptium releases
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, oca-signed

#321 Set types for workflow inputs
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: enhancement, testing, oca-signed

#322 CI: Switch to adoptium releases
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, oca-signed, affects/21.2

#323 CI: Switch to adoptium releases
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, oca-signed, affects/21.3

#324 CI: Change quarkus.version for Quarkus 2.2
  .github/update_quarkus_version.sh
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, oca-signed
