Repository graalvm/mandrel, pull requests merged in 2022-10, with the labels that each got.

#427 CI: Schedule nightly runs earlier and restrict permissions (hardening of CI)
  .github/workflows/mark-stale-issues-and-prs.yml
  .github/workflows/nightly.yml
  .github/workflows/repo-sync.yml
Labels: enhancement, testing

#431 CI: Fix permissions for repo-sync workflow
  .github/workflows/repo-sync.yml
Labels: OCA Verified

#433 CI: Update GitHub actions versions
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
  .github/workflows/repo-sync.yml
Labels: OCA Verified

#429 Upstream 21.3.3.1 merge
  common.json
  compiler/ci_common/gate.hocon
  tools/CHANGELOG.md
  tools/src/com.oracle.truffle.tools.agentscript/src/com/oracle/truffle/tools/agentscript/impl/InsightFilter.java
  tools/src/com.oracle.truffle.tools.agentscript/src/com/oracle/truffle/tools/agentscript/impl/InsightInstrument.java
  tools/src/com.oracle.truffle.tools.agentscript/src/com/oracle/truffle/tools/agentscript/impl/InsightPerContext.java
  tools/src/com.oracle.truffle.tools.agentscript/src/com/oracle/truffle/tools/agentscript/impl/InsightPerSource.java
  tools/src/org.graalvm.tools.insight.heap/src/org/graalvm/tools/insight/heap/instrument/HeapGenerator.java
  tools/src/org.graalvm.tools.insight.test/src/org/graalvm/tools/insight/test/heap/HeapObjectStreamTest.java
  tools/src/org.graalvm.tools.insight.test/src/org/graalvm/tools/insight/test/heap/HeapObjectTest.java
  truffle/external_repos/simplelanguage/pom.xml
  truffle/external_repos/simplelanguage/sl
  truffle/external_repos/simpletool/pom.xml
  truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/host/GR39979.java
  truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/polyglot/TruffleFileTest.java
  truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/FileSystems.java
  truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotExecuteNode.java
  vm/mx.vm/suite.py
Labels: OCA Verified

#434 Bump version to 21.3.4.0 [skip ci]
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#435 CI: Fix actions/cache version and bump actions/download-artifact
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#430 Adapt to CKeyStore.loadKeysOrCertificateChains signature change
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Labels: OCA Verified

#439 Mark suites for 21.3.4.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#438 CI: Update test matrix for Mandrel 21.3
  .github/workflows/mandrel.yml
Labels: OCA Verified

#440 CI: Fix job names (they should not contain dots)
  .github/workflows/mandrel.yml
Labels: OCA Verified

#441 CI: Stop testing Q main with 21.3, start testing Q 2.13 with 22.3-dev
  .github/workflows/nightly.yml
Labels: OCA Verified

#442 Mark suites for 22.3.0.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#443 Unmark suites and bump version to 22.3.0.1
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#444 Only require libmanagement_ext if it's actually needed.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationManagementExt.java
Labels: bug, backport, OCA Verified

#447 CI: Use JDK 17 to test GraalVM CE 22.3-dev with Quarkus 2.13
  .github/workflows/nightly.yml
Labels: OCA Verified

#448 CI: Only run mandrel integration tests with mandrel builds
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#449 CI: Remove left over chars from if condition
  .github/workflows/base.yml
Labels: OCA Verified

#450 CI: Add missing && in if condition
  .github/workflows/base-windows.yml
Labels: OCA Verified
