Repository graalvm/mandrel, pull requests merged in 2022-07, with the labels that each got.

#402 Add mandrel-bot GH token to secrets for reporting results on GH
  .github/workflows/nightly.yml
Labels: OCA Verified

#403 Only report failures to mandrel-integration-tests when Mandrel IT runs
  .github/quarkus-ecosystem-issue.java
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: enhancement, testing, OCA Verified

#410 Mark suites for 21.3.3.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#408 Mark suites for 22.2.0.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#413 CI: Support longpaths on Windows
  .github/workflows/base-windows.yml
Labels: testing, OCA Verified

#415 Unmark suites and bump version to 22.2.0.1
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#414 Unmark suites and bump version to 21.3.3.1
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified
