Repository graalvm/mandrel, pull requests merged in 2022-01, with the labels that each got.

#342 CI: Fix typo 's/suffices/suffixes/' and a comment
  .github/workflows/base-windows-wrapper.yml
  .github/workflows/base-windows.yml
  .github/workflows/base-wrapper.yml
  .github/workflows/base.yml
Labels: enhancement, testing, oca-signed

#347 Mark suites for 21.3.1.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: oca-signed

#351 Adjusted dependencies for RHEL 9:libstdc++-devel
  README.md
Labels: oca-signed

#354 Disable 22.0-dev nightly builds now that 22.0.0 is released
  .github/workflows/nightly.yml
Labels: testing
