Repository graalvm/mandrel, pull requests merged in 2023-12, with the labels that each got.

#626 Revert "[CI] Enable non time sensitive performance regression checks"
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#627 [CI] Don't try to upload stats when native-tests are not ran
  .github/workflows/base.yml
Labels: OCA Verified

#628 [CI] Enhance comments in "managed" github issues
  .github/quarkus-ecosystem-issue.java
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#630 [CI] Enhance comments in "managed" github issues v2
  .github/quarkus-ecosystem-issue.java
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
  .github/workflows/github-issue-updater.yml
Labels: OCA Verified

#631 [CI] Remove echo of triggering workflow run context
  .github/workflows/github-issue-updater.yml
Labels: OCA Verified

#632 [CI] Include maven ERROR messages in mandrel-integration-tests logs
  .github/quarkus-ecosystem-issue.java
Labels: OCA Verified

#641 [CI] Don't update file while reading it
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#638 [22.3] Backports for January CPU release
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ReachabilityHandlerFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java
Labels: backport, affects/22.3, OCA Verified

#640 [23.1] Backports for January CPU release
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/SimulateClassInitializerGraphDecoder.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/clinit/TestClassInitialization.java
Labels: backport, OCA Verified, affects/23.1

#639 [23.0] Backport: Throw exception for null pointers passed to RuntimeJNIAccess / RuntimeReflection register methods
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java
Labels: backport, OCA Verified, affects/23.0

#643 Only update ~/.docker/config.json if it exists
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: OCA Verified

#646 [CI] Schedule nightly workflows for mandrel/24 branch
  .github/workflows/nightly.yml
Labels: OCA Verified

#650 [CI] Report synchronization workflow failures on GitHub issues
  .github/quarkus-ecosystem-issue.java
  .github/workflows/github-issue-updater.yml
  .github/workflows/repo-sync.yml
Labels: OCA Verified

#648 [CI] Start using JDK 23 for Mandrel `graal/master` builds
  .github/workflows/base-windows-wrapper.yml
  .github/workflows/base-wrapper.yml
  .github/workflows/nightly.yml
Labels: OCA Verified
