Repository graalvm/mandrel, pull requests merged in 2023-01, with the labels that each got.

#464 CI: Start building latest mandrel with JDK 20
  .github/workflows/base-windows-wrapper.yml
  .github/workflows/base-wrapper.yml
  .github/workflows/nightly.yml
Labels: testing, OCA Verified

#465 CI: Stop testing GraalVM jdk-17 based builds, test jdk-20 based builds
  .github/workflows/nightly.yml
Labels: testing, OCA Verified

#467 Mark suites for 21.3.5.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#471 Unmark suites and bump version to 21.3.5.1
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#472 CI: Pin java version to 17 for Quarkus building
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, affects/JDK20

#473 CI: Make native tests depend on Mandrel/GraalVM build and get JDK jobs
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: enhancement, testing, OCA Verified

#474 Mark suites for 22.3.1.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#475 Mark suites for 21.3.5.1-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#477 Unmark suites and bump version to 21.3.5.2
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified
