Repository graalvm/mandrel, pull requests merged in 2023-11, with the labels that each got.

#589 [CI] Stop testing quay.io images and always build from source
  .github/workflows/weekly.yml
Labels: testing, OCA Verified

#610 [22.3] Fix `javax.crypto.JceSecurity` substitutions in JDK >= 17.0.10
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JceSecurityHasInnerClassIdentityWrapper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JceSecurityHasInnerClassWeakIdentityWrapper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Labels: OCA Verified

#609 [23.0] Fix `javax.crypto.JceSecurity` substitutions in JDK >= 17.0.10
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JceSecurityHasInnerClassIdentityWrapper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JceSecurityHasInnerClassWeakIdentityWrapper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Labels: OCA Verified

#606 [CI] Update nightly builds to use JDK 22
  .github/workflows/nightly.yml
  .github/workflows/weekly.yml
Labels: OCA Verified

#615 Add support for Windows extended socket options
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsNativeLibrarySupport.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/WindowsExtNetHelper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/JNILibraryInitializer.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJavaNet.java
Labels: release/noteworthy-feature, OCA Verified

#614 Add support for Windows extended socket options
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsNativeLibrarySupport.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/WindowsExtNetHelper.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/JNILibraryInitializer.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJavaNet.java
Labels: release/noteworthy-feature, OCA Verified

#616 [22.3] Stop deleting (Buddhist|JapaneseImperial)Calendar
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/CalendarSubstitutions.java
Labels: backport, OCA Verified

#620 Add jobs to report Mandrel build failures in Github issues
  .github/workflows/base-windows.yml
  .github/workflows/base.yml
Labels: testing, OCA Verified

#621 Fix weekly workflow
  .github/workflows/weekly.yml
Labels: testing, OCA Verified

#622 [CI] Revert temporary commit used for testing
  .github/workflows/nightly.yml
  .github/workflows/weekly.yml
Labels: OCA Required

#624 The Windows Mandrel IT issue is 207, not 208 (which is Linux)
  .github/workflows/nightly.yml
Labels: OCA Verified
