Repository graalvm/mandrel, pull requests merged in 2023-07, with the labels that each got.

#530 Sync 22.3 upstream branch with mandrel/22.3
  common.json
  compiler/mx.compiler/suite.py
  docs/graalvm-as-a-platform/implement-language.md
  docs/tools/ideal-graph-visualizer.md
  espresso/mx.espresso/suite.py
  regex/mx.regex/mx_regex.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/mx_sdk.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/AArch64CalleeSavedRegisters.java
  substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/AArch64FarReturnOp.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixSubstrateSegfaultHandler.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixSubstrateSigprofHandler.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixUtils.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/SunMiscSubstitutions.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateSegfaultHandler.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/VMOperation.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/methodhandles/MethodHandleFeature.java
  tools/mx.tools/suite.py
  tools/src/com.oracle.truffle.tools.chromeinspector.test/src/com/oracle/truffle/tools/chromeinspector/test/InspectorAddressTest.java
  tools/src/com.oracle.truffle.tools.chromeinspector.test/src/com/oracle/truffle/tools/chromeinspector/test/InspectorDnsRebindAttackTest.java
  tools/src/com.oracle.truffle.tools.chromeinspector.test/src/com/oracle/truffle/tools/chromeinspector/test/MultiEngineTest.java
  tools/src/com.oracle.truffle.tools.chromeinspector.test/src/com/oracle/truffle/tools/chromeinspector/test/RelativeSourceInspectDebugTest.java
  tools/src/com.oracle.truffle.tools.chromeinspector/src/com/oracle/truffle/tools/chromeinspector/server/InspectorServer.java
  truffle/external_repos/simplelanguage/pom.xml
  truffle/external_repos/simplelanguage/sl
  truffle/external_repos/simpletool/pom.xml
  truffle/mx.truffle/suite.py
  truffle/src/com.oracle.truffle.api.test/src/com/oracle/truffle/api/test/polyglot/ValueScopingTest.java
  truffle/src/com.oracle.truffle.host/src/com/oracle/truffle/host/HostMethodDesc.java
  truffle/src/com.oracle.truffle.host/src/com/oracle/truffle/host/HostToTypeNode.java
  truffle/src/com.oracle.truffle.host/src/com/oracle/truffle/host/HostUtil.java
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#524 [CI] Assign github issues to be automatically updated by nightly CI
  .github/workflows/nightly.yml
Labels: testing, OCA Verified

#533 Make graal-sdk artefact JDK 11+ compatible
  sdk/mx.sdk/suite.py
Labels: OCA Verified

#534 Bump version to 23.0.1.0 and mark as non-release [skip CI]
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#536 [23.0] Restore ability to disable debuginfo stripping
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoStripFeature.java
Labels: backport, OCA Verified

#535 Mark suites for 23.0.1.0-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#537 [CI] Pass mandrel-bot token to jobs opening/closing GH issues
  .github/workflows/nightly.yml
Labels: testing, OCA Verified

#539 Backport JFR ID bug fix
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrSymbolRepository.java
Labels: OCA Verified

#540 Unmark suites and bump version to 23.0.1.1
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#541 [23.0] Synchronization with upstream 23.0 branch for July CPU release
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64CounterModeAESCryptOp.java
  compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/EncodeArrayTest.java
  compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringGetBytesTest.java
  docs/README.md
  docs/getting-started/graalvm-community/container-images/graalvm-ce-container-images.md
  docs/getting-started/graalvm-community/windows.md
  docs/getting-started/graalvm-enterprise/windows.md
  docs/getting-started/img/desktop_development_with_C.png
  docs/getting-started/img/open_vs_installer.png
  docs/getting-started/img/visual-studio-installed-components.png
  docs/getting-started/img/visual_studio_installer.png
  docs/getting-started/img/windows-10-installed.png
  docs/img/github-web-editor.png
  docs/img/graalvm_architecture_community.png
  docs/reference-manual/native-image/BuildOptions.md
  docs/reference-manual/native-image/JFR.md
  docs/reference-manual/native-image/README.md
  docs/security/JipherJCE.md
  substratevm/src/com.oracle.svm.driver/resources/HelpExtra.txt
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ProgressReporter.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ProgressReporterFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/localization/LocalizationFeature.java
  truffle/mx.truffle/suite.py
  truffle/src/com.oracle.truffle.api.jdk20/src/com/oracle/truffle/api/impl/JDKAccessor.java
  truffle/src/com.oracle.truffle.api.jdk20/src/com/oracle/truffle/api/impl/JDKAccessorImpl.java
Labels: OCA Verified

#542 [22.3] Synchronization with upstream 22.3 branch for July CPU release
  common.json
  compiler/docs/Debugging.md
  compiler/mx.compiler/suite.py
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64CounterModeAESCryptOp.java
  compiler/src/org.graalvm.compiler.lir.amd64/src/org/graalvm/compiler/lir/amd64/AMD64CounterModeAESCryptOp.java
  compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/StringCompressInflateTest.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/InvocationPluginHelper.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/ReplacementsUtil.java
  docs/graalvm-as-a-platform/implement-language.md
  docs/tools/ideal-graph-visualizer.md
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisMethod.java
  substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/reflect/target/ReflectionMetadataDecoderImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionMetadata.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionMetadataEncoderImpl.java
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#547 Mark suites for 22.3.3.1-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#548 Mark suites for 23.0.1.1-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#549 Unmark suites and bump version to 23.0.1.2
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified

#550 [23.0] Synchronization with upstream 23.0 branch for July CPU release 2nd version
  common.json
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/UnimplementedGraalIntrinsics.java
  vm/mx.vm/suite.py
Labels: OCA Verified

#551 Mark suites for 23.0.1.2-Final release
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
Labels: OCA Verified

#553 Unmark suites and bump version to 23.0.1.3
  compiler/mx.compiler/suite.py
  espresso/mx.espresso/suite.py
  regex/mx.regex/suite.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/suite.py
  tools/mx.tools/suite.py
  truffle/mx.truffle/suite.py
  vm/mx.vm/suite.py
  wasm/mx.wasm/suite.py
Labels: OCA Verified
